---
- name : Deployment using docker image
  hosts : node2
  become : yes
    
  tasks:
   
   - name : create a conatiner
     command : docker container run -dt --name odessy -p 8080:8080 deepakkumarawsdevops/ansibledockerimage:01
...     
